### ISSUE TITLE
[Bug] mt-mods/technic missing energy values in MineClone2

### ISSUE THREAD

**Issue by programmerjake** [ThePython10110/ExchangeClone#13] opened 2024-01-10 06:56 UTC
**Describe the bug**
[mt-mods/technic just added MineClone2 support](https://github.com/mt-mods/technic/pull/328), ExchangeClone doesn't give energy values to items from technic when playing with MineClone2.

**Expected behavior**
Technic things such as Chromium Ingot have an energy value.

**Game (e.g. Minetest Game)**
MineClone2 0.86.2

**Reproduction Steps**
Get latest Git version of https://github.com/mt-mods/technic (not yet on ContentDB as of writing)
Create world with MineClone2.
Enable pipeworks, basic_materials, and the exchangeclone modpack.
Enable technic_worldgen and technic mods (the whole modpack doesn't work yet last I checked, just those two mods, which are enough to use it)
Start game
Get some chromium/uranium/sulfur/etc., cook into ingots where applicable.
Observe that they don't have any energy values.

**Comment by programmerjake** [comment] 2024-01-10 07:24
an additional bug I spotted: iron/gold nuggets often have a much larger energy value than the corresponding ingots, but this seems to be somewhat random each time the world is started. this may require mods other than just ExchangeClone to be enabled...maybe a mod loading order issue?

**Comment by ThePython10110** [comment] 2024-01-10 15:36
I guess I just forgot that Technic worked in MCL. The iron nuggets are due to the fact that the energy value for iron ingots is automatically generated, meaning that on the first iteration, iron nuggets get the energy value of the cheapest *available* recipe, which happens to be a random piece of chain armor. I'm not sure about the gold nuggets (and can't really reproduce it). This should be fixed now.

**Closed** 2024-01-10 15:36 UTC
Labels: bug
